#import "report_format.typ": *
#import "@preview/numbly:0.1.0": numbly
#import "@preview/codelst:2.0.0": sourcecode

// #import "@preview/physica:0.9.2"
#show: master_thesis.with(
  title: "Game Informatics",
  subtitle: "Report 3",
  author: "Tatsuya Kawaguchi",
  id: "2510414",
  university: "JAIST",
  bibliography-file: "bib\Game_Informatics_Report1.bib",
)

= Comparison between Newtonian mechanics and the theory of gravity in mind

Newtonian mechanics describes the motion of physical objects based on objective forces such as gravity.
In this framework, objects interact with each other according to universal and measurable laws, and their motion is determined by mass, force, and acceleration.

In contrast, the theory of gravity in mind extends this physical analogy to the realm of human cognition.
Rather than explaining the motion of physical objects, it explains the motion of things in the human mind, such as games, information, and experiences. Here, gravity does not represent a physical force but a cognitive attraction generated by uncertainty and expectation. This “gravity in mind” draws human cognition toward objectivity, such as a resolved outcome or understanding.

= Motion and interaction: objects, things, and human cognition

In Newtonian mechanics, interactions occur solely between objects.
These interactions are symmetric, objective, and independent of observation or interpretation. The motion of an object is unaffected by how it is perceived.

However, in the realm of mind, interaction occurs between human cognition and things.
Objects such as games or artifacts possess no intrinsic entertainment value by themselves; rather, their attractiveness emerges through interaction with the human mind. A thing with unresolved uncertainty generates cognitive potential energy, and the gravity in mind pulls human attention and emotion toward its resolution. At the same time, human cognition actively shapes the perceived attractiveness of the thing. In this sense, things influence the human mind, while the human mind simultaneously alters the meaning and appeal of things.

Furthermore, when interactions are mediated by a particular thing—such as a competitive game or a shared system—human cognition interacts with other human cognition.
The uncertainty generated by other people’s intentions, decisions, and emotions amplifies the gravity in mind, leading to stronger engagement and deeper immersion.

= Why people are strongly drawn to specific things and specific persons

From the perspective of the theory of gravity in mind, strong attraction arises when a thing sustains uncertainty over time and continuously converts cognitive potential energy into momentum.
Just as celestial bodies are bound by gravity, human cognition can become bound to a particular object that exerts a strong gravitational pull in the realm of mind.

This phenomenon can be understood through an analogy with celestial motion.
The Moon orbits the Earth because it is captured by Earth’s gravity; the Earth orbits the Sun, and the solar system orbits the galaxy under even greater gravitational influence. Similarly, when a person encounters a thing or an experience with exceptionally strong cognitive gravity, their attention and emotion begin to orbit around it. Other concerns lose significance, and the mind becomes increasingly absorbed in that single gravitational center.

The same explanation applies to the phenomenon of being captivated by a specific person.
Another person can function as a powerful gravitational source in the realm of mind because their thoughts, intentions, and emotions are inherently uncertain. This uncertainty generates high cognitive potential energy, and the gravity in mind draws one’s cognition toward the other person. As a result, the individual may become deeply absorbed, finding it difficult to think about anything else.

Thus, while Newtonian gravity governs the motion of objects in the physical universe, the theory of gravity in mind explains attraction as a cognitive phenomenon driven by uncertainty.
People are drawn not merely to objects or persons themselves, but to the gravitational pull created by unresolved possibilities within the realm of mind.